### ISSUE TITLE
isSubmitting stuck on FALSE if exception thrown in Promise

### ISSUE THREAD

**Issue by PizzaConsole** [mateenagy/vue-formify#7]
> @mateenagy  I think this should be in a try-catch-finally. If the promise throws an exception it might never set the form back to isSubmitting = false
> 
> (have not been able to test it yet) 

 _Originally posted by @PizzaConsole in [94e2fd5](https://github.com/mateenagy/vue-formify/commit/94e2fd5703c396172736f805458c11ccc79cf1aa#r148441346)_

**Comment by mateenagy** [comment]
It's not stuck on false because the submit method inside the `Form` component handle this. Actually I don't even need to set the `isSubmitting` inside the `handleSubmit` function.

The reason it's working is because when you use the `handleSubmit` from `useForm` it will be the `onSubmit` event inside the `submit` method which is wrapped between a `try catch`. 

I tested it and it's working both way so I close this issue but feel free to reopen or open a new one if you find something.

**Comment by PizzaConsole** [comment]
@mateenagy I tested it and it gets stuck in Submitting

```<template>
  <FormifyForm @submit="submit">
    <Field name="username" />
    <FieldError error-for="username" />
    {{ isSubmitting ? 'Submitting...' : '' }}
    <button :disabled="isSubmitting">Send</button>
  </FormifyForm>
</template>

<script setup lang="ts">
import { FormifyForm, useForm } from 'vue-formify';

type LoginRequest = {
  username: string;
};
const { Form, Field, Error: FieldError, handleSubmit, isSubmitting } = useForm<LoginRequest>();
const promiseSubmit = async () => {
  throw new Error('test');
};
const submit = handleSubmit(async (data) => {
  await promiseSubmit();
  console.log('[data]: ', data);
});
</script>
```

**Comment by mateenagy** [comment]
@PizzaConsole The main problem you are mixed the `FormifyForm` from the main package and the `Field` from the composable. The `Form` from the package directly and from the composable have slightly different logic under the hood because of the type-safety nature so you cant mix the two. (I will update the docs to make it more clear).

So this code working without stuck on `false`:
```vue
<template>
  <Form @submit="submit">
    <Field name="" />
    <FieldError error-for="username" />
    {{ isSubmitting ? 'Submitting...' : '' }}
    <button :disabled="isSubmitting">Send</button>
  </Form>
</template>

<script setup lang="ts">
import { useForm } from 'vue-formify';

type LoginRequest = {
  username: string;
};
  const { Form, Field, Error: FieldError, handleSubmit, isSubmitting } = useForm<LoginRequest>();
  const promiseSubmit = async () => {
    return new Promise((_, reject) => {
      setTimeout(() => {
        reject(new Error('test'));
      }, 1000);
    });
  };
  const submit = handleSubmit(async (data) => {
    await promiseSubmit();
    console.log('[data]: ', data);
  });
</script>
```vue

**Comment by PizzaConsole** [comment]
Gotcha, just getting over the learning curve on my side then.

**Comment by mateenagy** [comment]
No problem, this is my first big open source project so I also need to learn to write better documentation to make different mechanics more clear and make the learning curve easier. I hope you like it so far.
