### ISSUE TITLE
Request - Rename Error to FieldError for clarity

### ISSUE THREAD

**Issue by PizzaConsole** [mateenagy/vue-formify#8]
Title says it all. It would be my preference, have the "Error" rename to "FieldError" as to not overlap the native `Error` object. Better yet might be to maybe prefix all the Tag like the `FormifyForm` like `FormifyField` - `FormifyFieldError` - `FormifyFieldArray` 

Maybe something similar for the useForm? Just a suggestion

**Comment by mateenagy** [comment]
In the first iteration of the package everything had the `Formify` prefix, but after a while it felt more nicer to my eye and preference to use simple naming (I know it's against the vue style guide because it's prefer multi-word names) so that is why I start to use these naming. I left `FormifyForm` for easier backwards compatibility for myself. 😄

I will leave it that way now, but later if it requested by more user I will reconsider this decision.
